// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYDNBvPSzXrtiNNKRGuNfWCleoS1nIUXk',
    appId: '1:417950745661:web:02c435eb5527db17545654',
    messagingSenderId: '417950745661',
    projectId: 'spotter-5f58c',
    authDomain: 'spotter-5f58c.firebaseapp.com',
    storageBucket: 'spotter-5f58c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9fbVQBWKzaXK7bL_tpaUvkcImyuq9qpg',
    appId: '1:417950745661:android:fe6b296878aed8c0545654',
    messagingSenderId: '417950745661',
    projectId: 'spotter-5f58c',
    storageBucket: 'spotter-5f58c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAceA7JfIHP6etXKkAZ5DJOSmjYpO8rbDA',
    appId: '1:417950745661:ios:81e6032bbcac23a7545654',
    messagingSenderId: '417950745661',
    projectId: 'spotter-5f58c',
    storageBucket: 'spotter-5f58c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAceA7JfIHP6etXKkAZ5DJOSmjYpO8rbDA',
    appId: '1:417950745661:ios:81e6032bbcac23a7545654',
    messagingSenderId: '417950745661',
    projectId: 'spotter-5f58c',
    storageBucket: 'spotter-5f58c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYDNBvPSzXrtiNNKRGuNfWCleoS1nIUXk',
    appId: '1:417950745661:web:685f2736635a90ce545654',
    messagingSenderId: '417950745661',
    projectId: 'spotter-5f58c',
    authDomain: 'spotter-5f58c.firebaseapp.com',
    storageBucket: 'spotter-5f58c.firebasestorage.app',
  );
}
